baseurl = "http://ocp.opennetlinux.org/"
languageCode = "en-us"
title = "Open Network Linux"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/opencomputeproject/OpenNetworkLinux"

	version = "2.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "opennetlinux"
	github  = "opennetworklinux"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
        name   = "Download Binaries"
        url    = "http://opennetlinux.org/binaries/"
        weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "FAQ"
	url    = "faq/"
	weight = 30

[[menu.main]]
        name   = "Community"
        url    = "community/"
        weight = 40

[[menu.main]]
        name   = "Blog"
        url    = "blog/"
        weight = 50

[[menu.main]]
	name   = "Wedge"
	url    = "wedge/"
	weight = 60

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 70


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
